"""Deterministic local TETR.IO-compatible rules primitives."""

from .state import (
    Board,
    BotStandardPreset,
    GarbagePacket,
    GameState,
    Piece,
    PlayerState,
    Ruleset,
    StreakState,
    stable_json,
)
from .rules import (
    LockResult,
    Placement,
    can_place,
    classify_t_spin,
    hard_drop,
    hold_current_piece,
    initial_game_state,
    is_top_out,
    lock_piece,
    piece_cells,
    rotate_placement,
    seven_bag,
)
from .movegen import Candidate, Move, generate_candidates, replay_path, validate_move

__all__ = [
    "Board",
    "BotStandardPreset",
    "GarbagePacket",
    "GameState",
    "Piece",
    "PlayerState",
    "Ruleset",
    "StreakState",
    "stable_json",
    "LockResult",
    "Placement",
    "can_place",
    "classify_t_spin",
    "hard_drop",
    "hold_current_piece",
    "initial_game_state",
    "is_top_out",
    "lock_piece",
    "piece_cells",
    "rotate_placement",
    "seven_bag",
    "Candidate",
    "Move",
    "generate_candidates",
    "replay_path",
    "validate_move",
]
